export const servicesData = [
  {
    id: 1,
    titleKey: "clinicService.generalTitle",
    textKey: "clinicService.generalText",
    title: "Stomatologji e Përgjithshme",
    text: "Kontrolle, pastrime dhe trajtime rutinë për ruajtjen e shëndetit oral afatgjatë.",
    numberColor: "text-[#2e8e84]",
  },
  {
    id: 2,
    titleKey: "clinicService.implantsTitle",
    textKey: "clinicService.implantsText",
    title: "Zgjidhje me Implante",
    text: "Zëvendësim i sigurt dhe afatgjatë i dhëmbëve të munguar me implante natyrale.",
    numberColor: "text-[#b78148]",
  },
  {
    id: 3,
    titleKey: "clinicService.cosmeticTitle",
    textKey: "clinicService.cosmeticText",
    title: "Dentistri Kozmetike",
    text: "Përmirësoni estetikën e buzëqeshjes me veneers, bonding dhe trajtime moderne kozmetike.",
    numberColor: "text-[#2e8e84]",
  },
  {
    id: 4,
    titleKey: "clinicService.whiteningTitle",
    textKey: "clinicService.whiteningText",
    title: "Zbardhim Dhëmbësh",
    text: "Trajtime profesionale për një buzëqeshje më të bardhë, të ndritshme dhe më të sigurt.",
    numberColor: "text-[#b78148]",
  },
  {
    id: 5,
    titleKey: "clinicService.pediatricTitle",
    textKey: "clinicService.pediatricText",
    title: "Stomatologji Pediatrike",
    text: "Kujdes i specializuar dhe miqësor për fëmijët në çdo fazë të zhvillimit dentar.",
    numberColor: "text-[#2e8e84]",
  },
  {
    id: 6,
    titleKey: "clinicService.advancedTitle",
    textKey: "clinicService.advancedText",
    title: "Kujdes Oral i Avancuar",
    text: "Trajtime të avancuara për zgjidhjen e problemeve komplekse dentare dhe orale.",
    numberColor: "text-[#b78148]",
  },
  {
    id: 7,
    titleKey: "clinicService.comfortTitle",
    textKey: "clinicService.comfortText",
    title: "Stomatologji Komode",
    text: "Përvojë dentare e qetë dhe pa stres në një ambient modern dhe mikpritës.",
    numberColor: "text-[#2e8e84]",
  },
  {
    id: 8,
    titleKey: "clinicService.emergencyTitle",
    textKey: "clinicService.emergencyText",
    title: "Kujdes Emergjent",
    text: "Ndihmë e menjëhershme për dhimbje, trauma dhe urgjenca dentare.",
    numberColor: "text-[#b78148]",
  },
];
